# This is a basic workflow to help you get started with Actions

name: clash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
  schedule:
    - cron: '*/2 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  stash:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        # git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        run: |
          git config --local user.email "weijinsun@gmail.com"
          git config --local user.name "svj"
          git remote set-url origin https://github.com/weijinsun/forclash.git
          git pull --rebase
          git commit --allow-empty -m "~~~"
          git push
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: weijinsun/forclash@main
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ls -la
          echo '-----------'
          cd /home/runner/work/_actions/weijinsun/forclash/main
          ls -la
          cd ..
